// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkaDnnd_Eo04mwDEF8ZtwLKYp5Xxa6gr4',
    appId: '1:772075656690:web:c127fec5a5cf16bc65076b',
    messagingSenderId: '772075656690',
    projectId: 'cherishcarecare',
    authDomain: 'cherishcarecare.firebaseapp.com',
    storageBucket: 'cherishcarecare.firebasestorage.app',
    measurementId: 'G-Q3S99DTDXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNMP3ZG_eciUuhYXT3Bp2_hJZhvSvRzII',
    appId: '1:772075656690:android:ac4320884767705965076b',
    messagingSenderId: '772075656690',
    projectId: 'cherishcarecare',
    storageBucket: 'cherishcarecare.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhpmjmvFY-h-5u7BOSymmXpV9AAp33848',
    appId: '1:772075656690:ios:fe8ac509315cfade65076b',
    messagingSenderId: '772075656690',
    projectId: 'cherishcarecare',
    storageBucket: 'cherishcarecare.firebasestorage.app',
    iosBundleId: 'com.example.cherichCare2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhpmjmvFY-h-5u7BOSymmXpV9AAp33848',
    appId: '1:772075656690:ios:fe8ac509315cfade65076b',
    messagingSenderId: '772075656690',
    projectId: 'cherishcarecare',
    storageBucket: 'cherishcarecare.firebasestorage.app',
    iosBundleId: 'com.example.cherichCare2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkaDnnd_Eo04mwDEF8ZtwLKYp5Xxa6gr4',
    appId: '1:772075656690:web:2de27d7bb0b3d5ad65076b',
    messagingSenderId: '772075656690',
    projectId: 'cherishcarecare',
    authDomain: 'cherishcarecare.firebaseapp.com',
    storageBucket: 'cherishcarecare.firebasestorage.app',
    measurementId: 'G-Y89LP2Q1FV',
  );
}
